version: '2.4'

services:

  # latency-monitor
  latency-monitor:
    container_name: latency-monitor
    hostname: latency-monitor
    build: ./Docker_Build
    restart: always
    volumes:
      # - ./latency-monitor/config.ini:/app/config.ini:ro # UNCOMMENT IF NEEDED
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - INFLUX_URL
      - INFLUX_TOKEN
      - INFLUX_BUCKET
      - INFLUX_ORG
      - TARGET_HOST
      - TARGET_TIMER
      - TARGET_LOCATION